# Site settings
title: Tim Kendrick
subtitle: JavaScript Engineer
email: timkendrick@gmail.com
description: "Tim Kendrick, JavaScript Software Engineer / Interactive Developer"
baseurl: ""
url: "http://timkendrick.co.uk"
linkedin:
  id: "192494997"
  name: "Tim Kendrick"
twitter_username:
github_username: timkendrick
npm_username:

# File settings
exclude: ["node_modules", "package.json", "README.md"]

# Build settings
permalink: /articles/:year/:month/:day/:title.html
markdown: kramdown

kramdown:
  input: GFM

# Content settings
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: article
      class: -article
      bodyClass: article

# Preview settings
host: 0.0.0.0
